pipeline {
    agent any 
    parameters {
        string defaultValue: 'main', name: 'test', trim: true
   }
 
   environment {
      BRANCH_NAME = "${BRANCH}"
   }
  
    stages {
        stage('STAGE-1') {
            when {
                branch 'main'
            }
            steps{
                sh "echo STEGE-1 executes if branch is main $BRANCH_NAME"
            }
        }

        stage('STAGE-2'){
            when {
                branch 'test'
            }
            steps{
                sh "echo STEGE-2 executes if branch is test $BRANCH_NAME"
            }
        }
    }
}
