pipeline {
  agent any
  
  stages {
    stage('build') {
      when {
        branch 'master'
      }
      steps {
        sh 'echo "Building..."'
      }
    }
    
    stage('test') {
      when {
        branch 'master'
      }
      steps {
        sh 'echo "Testing..."'
      }
    }
  }
}
