pipeline {
    agent any
    environment {
        host = "54.238.78.182"
    }

    
    stages{
        stage('BUILD') {
            
            agent { label 'master' }
            
            steps{
                 sh '''
                    sleep 5
                    echo "This is a BUILD stage $host "
                '''
            }
        }

        stage('TEST') {
            
            agent { label 'slave1' }
            
            steps {
                sh '''
                    sleep 10
                    echo "This is a TEST stage $host "
                '''
            }
        }

        stage('DEPLOY') {
            
            agent { label 'slave2' }

            steps{
                sh '''
                    sleep 5
                    echo "This is a DEPLOY stage $host"
    
                '''
            }
        }
    }
}
