pipeline {
    agent none
    
    parameters {
     string defaultValue: 'main', name: 'branch', trim: true
    }
    
    environment {
        BRANCH_NAME = "$branch"
    }

    
    stages{
        stage('BUILD') {
            catchError(message: message, buildResult: 'SUCCESS', stageResult: 'FAILURE'){
                agent { label 'master' }
            
                steps{
                 sh '''
                    sleep 5
                    echo "This is a BUILD stage $BRANCH_NAME "
                    exit 1
                 '''
                }   
            }
        }

        stage('TEST') {

            parallel{

                stage('TEST ON LINUX MACHINE'){
            
            
                       agent { label 'slave1' }
            
                     steps { 
                      sh '''
                      sleep 10
                       echo "This is a TEST on LINUX"
                         '''
                       }
                }   
            
        
                    stage('TEST ON WINDOWS MACHINE'){
            
            
                       agent { label 'slave1' }
            
                       steps { 
                          sh '''
                            sleep 10
                            echo "This is a TEST on WINDOWS "
                              '''
                        }
                    }
            } 
        }    

        stage('DEPLOY') {
            
            agent { label 'slave2' }

            steps{
                sh '''
                    sleep 5
                    echo "This is a DEPLOY stage $BRANCH_NAME"
    
                '''
            }
        }
    }
}
