pipeline {
    agent any
    
    environment {
       HOST = "13.231.254.79"
          }

    stages{
        stage('BUILD') {
            
            agent { label 'master' }
            
            steps{
                 sh '''
                    sleep 5
                    echo "This is a BUILD stage $HOST"
                '''
            }
        }

        stage('TEST') {
            
            agent { label 'slave1' }
            
            steps {
                sh '''
                    sleep 10
                    echo "This is a TEST stage $HOST"
                '''
            }
        }

        stage('DEPLOY') {
            
            agent { label 'slave2' }

            steps{
                sh '''
                    sleep 5
                    echo "This is a DEPLOY stage $HOST"
    
                '''
            }
        }
    }
}
